services:

  app:
    build:
      context: .
    container_name: rumbos-backend
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - app/.env
    ports:
      - "8001:8000"
    networks:
      - rumbos-network

  db:
    image: postgres:17-alpine
    container_name: rumbos-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-rumbos:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    networks:
      - rumbos-network

volumes:
  postgres-rumbos:

networks:
  rumbos-network:
    driver: bridge
    external: true
