"""add course_maps and bubbles

Revision ID: ffbafbaf2f65
Revises: 8ff3bdc9ba08
Create Date: 2026-10-02 11:13:49.934097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffbafbaf2f65'
down_revision: Union[str, Sequence[str], None] = '8ff3bdc9ba08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_maps',
    sa.Column('moodle_course_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_maps_moodle_course_id'), 'course_maps', ['moodle_course_id'], unique=True)
    op.create_table('bubbles',
    sa.Column('course_map_id', sa.Uuid(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('x', sa.Double(), nullable=False),
    sa.Column('y', sa.Double(), nullable=False),
    sa.Column('icon', sa.Enum('question', 'chest', 'star', 'flag', 'book', 'video', 'trophy', 'lock', name='bubbleicon', native_enum=False, length=20), nullable=True),
    sa.Column('status', sa.Enum('locked', 'no_complete', 'in_progress', 'complete', name='bubblestatus', native_enum=False, length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('x >= 0 AND x <= 1', name='ck_bubbles_x_range'),
    sa.CheckConstraint('y >= 0 AND y <= 1', name='ck_bubbles_y_range'),
    sa.ForeignKeyConstraint(['course_map_id'], ['course_maps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bubbles_course_map_id'), 'bubbles', ['course_map_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bubbles_course_map_id'), table_name='bubbles')
    op.drop_table('bubbles')
    op.drop_index(op.f('ix_course_maps_moodle_course_id'), table_name='course_maps')
    op.drop_table('course_maps')
    # ### end Alembic commands ###
